---
- name: postgresql repository is enabled
  yum: name=http://yum.postgresql.org/{{postgresql_version}}/redhat/rhel-6-x86_64/pgdg-centos{{postgresql_version|replace('.','')}}-{{postgresql_version}}-1.noarch.rpm state=present

- name: postgresql is installed
  yum: name={{item}} state=present
  with_items:
    - postgresql{{postgresql_version|replace('.','')}}
    - postgresql{{postgresql_version|replace('.','')}}-contrib
    - postgresql{{postgresql_version|replace('.','')}}-devel
    - postgresql{{postgresql_version|replace('.','')}}-libs
    - postgresql{{postgresql_version|replace('.','')}}-python
    - postgresql{{postgresql_version|replace('.','')}}-server

- name: postgresql PATH is set up
  sudo_user: "{{user}}"
  lineinfile: dest=/home/{{user}}/.zshenv insertafter=EOF line="export PATH=/usr/pgsql-{{postgresql_version}}/bin:$PATH"
