---
- name: postgresql repository is enabled
  yum: name=http://yum.postgresql.org/{{postgresql_version}}/redhat/rhel-6-x86_64/pgdg-centos{{postgresql_version|replace('.','')}}-{{postgresql_version}}-1.noarch.rpm state=present

- name: postgresql is installed
  yum: name={{item}} state=present
  with_items:
    - postgresql{{postgresql_version|replace('.','')}}
    - postgresql{{postgresql_version|replace('.','')}}-contrib
    - postgresql{{postgresql_version|replace('.','')}}-devel
    - postgresql{{postgresql_version|replace('.','')}}-libs
    - postgresql{{postgresql_version|replace('.','')}}-python
    - postgresql{{postgresql_version|replace('.','')}}-server

- name: initdb is executed
  command: service postgresql-{{postgresql_version}} initdb creates=/var/lib/pgsql/{{postgresql_version}}/data/postgresql.conf

- name: postgresql service is enabled
  service: name=postgresql-{{postgresql_version}} enabled=yes state=started
