#!/bin/bash

if [ -z "${TARGET_HOST}" ]; then
  echo "TARGET_HOST is not defined"
  exit 1
fi

host=`cat ~/.ssh/config | grep -e "Host ${TARGET_HOST}" -A 1 | awk '$1 == "HostName" { print $2 }'`
if [ -z "$host" ]; then
  host=$TARGET_HOST
fi

cat <<INVENTORY
{
  "all": {
    "hosts": [ "$host" ]
  }
}
INVENTORY
