---
# role for my account
- name: my account is created
  user: name={{user}}

- name: public keys is downloaded
  get_url: url=https://github.com/kawaken.keys dest=/tmp/{{user}}_pubkeys
  delegate_to: localhost

- name: authorized_keys is set up
  authorized_key: user={{user}} key="{{ lookup('file', '/tmp/'+user+'_pubkeys') }}"

- name: dotfiles is downloaded
  sudo_user: "{{user}}"
  git: repo="https://github.com/kawaken/dotfiles.git" dest=dotfiles

- name: files in dotfiles are symbolic link
  sudo_user: "{{user}}"
  file: src={{item}} dest="/home/{{user}}/{{item|basename|replace('_', '.')}}" state=link
  with_fileglob:
    - /home/{{user}}/dotfiles/_*

