---
- name: required packages is installed
  yum: name={{item}}
  with_items:
    - MySQL-python

- name: latest wordpress is downloaded
  get_url: url=http://ja.wordpress.org/latest-ja.tar.gz dest=/usr/local/src/wordpress-latest.tar.gz

- name: wordpress-latest.tar.gz is unarchived
  command: tar xf wordpress-latest.tar.gz
  args:
    chdir: /usr/local/src
    creates: /usr/local/src/wordpress

- name: random salts is fetched
  sudo: false
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"

- name: read mysql root password
  shell: cat mysql_root_password
  register: mysql_root_password

- name: generate wordpress db password
  password: dest=wordpress_db_password

- name: read wordpress db password
  shell: cat wordpress_db_password
  register: wordpress_db_password

- name: wordpress database is created
  mysql_db: name={{wordpress_db_name}} state=present login_user=root login_password={{mysql_root_password.stdout}}

- name: wordpress database user
  mysql_user: name={{ wordpress_db_user }} password={{ wordpress_db_password.stdout }} priv={{ wordpress_db_user }}.*:ALL host='localhost' state=present login_user=root login_password={{mysql_root_password.stdout}}

- name: wordpress site is in public directory
  command: mv /usr/local/src/wordpress /var/www/{{wordpress_site_name}}
  args:
    creates: /var/www/{{wordpress_site_name}}

- name: config file is copied
  template: src=wp-config.php dest=/var/www/{{wordpress_site_name}}/wp-config.php

- name: log directory is created
  file: path=/var/www/{{wordpress_site_name}}/log state=directory

- name: onwer is changed
  file: path=/var/www/{{wordpress_site_name}}/ owner=nginx group=nginx state=directory recurse=yes

- name: nginx config is set up
  template: src=wordpress.conf dest=/etc/nginx/conf.d/wordpress.conf
