---
- name: mysql repository is enabled
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present

- name: default mysql is removed
  yum: name={{item}} state=absent
  with_items:
    - mysql
    - mysql-devel
    - mysql-libs

- name: mysql community version is installed
  yum: name={{item}} state=latest
  with_items:
    - "mysql-community-common"
    - "mysql-community-client"
    - "mysql-community-devel"
    - "mysql-community-libs"
    - "mysql-community-server"

- name: mysql server is enabled
  service: name=mysqld enabled=yes state=started

- name: generate mysql root password
  password: dest=mysql_root_password

- name: read mysql root password
  shell: cat mysql_root_password
  register: mysql_root_password

- name: mysql root password file is set up in tmp
  template: src=mysql_secure_installation.j2
    dest=/tmp/mysql_secure_installation
    owner=root group=root mode=0600

- name: mysql_secure_installation is called
  shell: cat /tmp/mysql_secure_installation | mysql_secure_installation

- name: remote tempfile
  shell: rm -f /tmp/mysql_secure_installation

- name: decrease table_definition_cache
  lineinfile: dest=/etc/my.cnf insertafter="[mysqld]" line="table_definition_cache=400"

- name: mysql server is restarted
  service: name=mysqld enabled=yes state=restarted

